/*
S2V Common Constants
*/
public class Commonconstant
{
    public static string futurecall = 'Future Call';
    public static string idlookup= 'Id';
    public static string campaignMember= 'CampaignMember';
    public static string task= 'Task';
    public static string completed= 'Completed';
    public static String contactmanually = 'Contact Manually';
    public static string inProgress= 'Not Started';
    public static string normal= 'Normal';
    public static string autosubs= 'Automated S2VM Voicemail Sent';
    public static String smstitle = 'Automated S2VM SMS Sent';
    public static string lead = 'Lead';
    public static string Contact = 'Contact';
    public static string Opportunity = 'Opportunity';
    public static string none = 'None';
    public static string optionSchedule = 'now';  
    public static string status = 'Queue';
    public Static boolean stopNotificationcheckbox = false;
}